version: '3'
services:
#mssql docker
  prodajaracopreme-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Enterprise
    ports:
      - 1401:1433
    networks:
      - prodajaracopremenet

  prodajaracopreme-api:
    restart: unless-stopped
    build:
      context: .
    environment:
     - ConnectionStrings:connectionpc=Server=prodajaracopreme-sql,1433;Database=170110;User=sa;Password=QWElkj132!;ConnectRetryCount=254
    ports:
      - 5000:80
    networks:
      - prodajaracopremenet    
    links:
      - prodajaracopreme-sql
    depends_on:
      - prodajaracopreme-sql
      
networks:
  prodajaracopremenet:
    driver: bridge 